### ISSUE TITLE
New issue | DECODE_PERCENTS  is not working on Azure devops agent Version 2.181.2

### ISSUE THREAD

**Issue by kohithms** [microsoft/azure-pipelines-agent#3270]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

I am using the below yaml file. 
======================
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
 - name : system.debug
   value : true
 - name : skipComponentGovernanceDetection
   value: true
 - name: DECODE_PERCENTS
   value: true

jobs:
- job:
  variables:
  - name: DECODE_PERCENTS
    value: true

  steps:
  - powershell: Write-Host '##vso[task.setvariable variable=test]a%AZP25'
    displayName: 'Set Variable'

  # This will print the a% correctly as the value of test
  - powershell: 'Get-ChildItem env:'
    displayName: 'printenv'

======================

When I am running on the Microsoft Hosted agents ( V2.181.2) system is not able to decode the value of the test. It's still printing as "a%AZP25" , Please finds the below screenshot for the same. 
Agent details : 

![image](https://user-images.githubusercontent.com/51953513/108213223-cae30800-7154-11eb-96bc-b247660d5fdb.png)

Variable output: 

![image](https://user-images.githubusercontent.com/51953513/108213275-d7676080-7154-11eb-8140-e693cf896578.png)

![image](https://user-images.githubusercontent.com/51953513/108210979-2f509800-7152-11eb-9c61-f633ee394811.png)

When I am using the self hosted agent V2.181.1 , system is displaying the value as ""
Self Hosted agent version : 

![image](https://user-images.githubusercontent.com/51953513/108212936-7cce0480-7154-11eb-94d5-dfdf08b43504.png)

Variable output:

![image](https://user-images.githubusercontent.com/51953513/108213075-a71fc200-7154-11eb-85f1-183c2445028d.png)

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Agent Version and Platform
Version of your agent? 2.181.2

OS of the machine running the agent? OSX/Windows/Linux/... Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
Dev.azure.com/kohithfs

## What's not working?
Please include error messages and screenshots.

> Variable  "DECODE_PERCENTS " is not working on Agent V2.181.2 whereas its working on V2.181.1

Tested on platforms : 

    vmImage: 
                     'windows-latest'
                     'macOS-latest'
                     'ubuntu-latest'

**_Reference Links :_**  

https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md

https://github.com/Microsoft/azure-pipelines-agent/releases

https://github.com/microsoft/azure-pipelines-agent/tree/releases/2.181.2

**Key URL : https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Knob/AgentKnobs.cs**

https://github.com/microsoft/azure-pipelines-agent/commit/9852cea2ab09f1efbd514db7e0ed3a5b02cc2330#diff-e9f1aa1a3ae52b26e46536b534890cf3e4957c7008a05fd36c65e6de7b6afa8f

**Comment by kohithms** [comment]
[https://github.com/microsoft/azure-pipelines-agent/commit/6dd5c59e042b437f1d639aaaa84879cf82886385](url)

[https://github.com/microsoft/azure-pipelines-agent/issues](url)

**Comment by damccorm** [comment]
Hey @kohithms this change was applied in agent release 2.182.1, it looks like you're using version 2.181.2 in your example, so it shouldn't have the change yet

**Comment by temelj** [comment]
We have two different agent pools and the % encoding was fixed using the `DECODE_PERCENTS:true` successfully using 2.181.1.

We have updated one of our pools to 2.182.1 and now the build pipeline is encoding % incorrectly again.

It's around retrieving the SAS token for storage account, i'm observing %25253A in the response.

**Comment by kohithms** [comment]
Hi @damccorm,

Thanks for confirming that but even on agent version 2.181.1 we are able to see the value as 

![image](https://user-images.githubusercontent.com/51953513/108513333-77092800-72e8-11eb-99e3-784c5ff97a28.png)

**Comment by damccorm** [comment]
Hey @kohithms I'm not able to reproduce this behavior. Here's an example pipeline - https://dev.azure.com/damccorm-repros/setVariable%20escaping/_build/results?buildId=1029&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43, driven off of this yaml file - https://dev.azure.com/damccorm-repros/_git/setVariable%20escaping?path=%2Fazure-pipelines.yml.

Would you mind attaching the yaml file you're using, as well as the full build logs?

**Comment by kohithms** [comment]
Hello @damccorm ,

Thanks for sharing the sample pipeline. In the given pipeline agent is using 2.182.1 looks like the issue is addressed over there. 
![image](https://user-images.githubusercontent.com/51953513/108676663-971a3080-750e-11eb-8561-6572ba169872.png)


But in version 2.181.1 it's still reproducible. 

![image](https://user-images.githubusercontent.com/51953513/108676689-a00b0200-750e-11eb-9e53-871eda2fdcf3.png)


![image](https://user-images.githubusercontent.com/51953513/108676777-c29d1b00-750e-11eb-904e-0541c0e447a5.png)




**Sample Pipeline:** 

https://dev.azure.com/KohithFS/test/_build/results?buildId=42017&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43

**Comment by kohithms** [comment]
Hi @damccorm, have u gt a chance to view this?

**Comment by mrlioncub** [comment]
Reproduced on the agent version: '2.195.2'
