### ISSUE TITLE
Failure to get lock fails installation

### ISSUE THREAD

**Issue by lonevvolf** [microsoft/azure-pipelines-agent#3560]
https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs#L522

Referring to the line above, if the SCM is busy at the time the agent tries to register/update properties, the installation doesn't complete , and doesn't wait/retry to get a lock.  We are hitting this constantly when spinning up new agents in a scale set using the method described here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
using the scripts from Microsoft found here:
https://github.com/actions/virtual-environments/tree/main/images

The image is based on Windows 2019 (10.0.17763), which makes this all the stranger, since the documentation for the function call here:
https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-lockservicedatabase
says: "[As of Windows Vista, this function is provided for application compatibility and has no effect on the database.]".

The relevant log info:
```
[2021-10-03 23:04:29Z INFO Terminal] WRITE LINE: Service vstsagent.Ucss.xxx-azdevops-pool.azdevops-1234XX successfully installed
[2021-10-03 23:04:29Z ERR  Agent] System.InvalidOperationException: Failed to Lock Service Database for Write
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.NativeWindowsServiceHelper.InstallService(String serviceName, String serviceDisplayName, String logonAccount, String logonPassword)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.WindowsServiceControlManager.ConfigureService(AgentSettings settings, CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2021-10-03 23:04:29Z ERR  Terminal] WRITE ERROR: Failed to Lock Service Database for Write
```

See also:
https://github.com/microsoft/azure-pipelines-agent/issues/3063

**Comment by aok-foss** [comment]
The issue also sporadically occurs on Windows Server 2022 (just got it on 10.0.20348 Build 350) and makes automated deploying of build agents a pain.

**Comment by aok-foss** [comment]
The error check actually seems a bit suspicious:

https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs#L523

The returned value is checked to be "non-negative", as if it was an HRESULT, yet the documentation of `LockServiceDatabase` function states that the only value returned in case of error is NULL.

Shouldn't the error check be `svcLock == IntPtr.Zero`?

Same goes for `OpenSCManager` and `CreateService` invocations in that class.

**Comment by anatolybolshakov** [comment]
Hi @lonevvolf @aok-foss thanks for reporting! We are currently working on more prioritized issues, but will get back to this one once be able to.

**Comment by lonevvolf** [comment]
This is not stale

**Comment by yirmio** [comment]
We are facing the same issue in all our new VMSS pools.
Sometimes almost 40% of the new agents are failing on this error.
Is there any plan to fix this issue?

**Comment by ceciliasharp** [comment]
Still an issue for a lot it seems. Also running on W2019 if that is relevant.

**Comment by yirmio** [comment]
I've opened a support ticket to MS on this matter, waiting for a proper response and will update here once will be recieved.

**Comment by yirmio** [comment]
Update from MS:
A fix will be merged by few days, but agent release may be delayed. The 2.215.0 release is scheduled for release in 2 weeks

**Comment by ceciliasharp** [comment]
Great support! My customer will be pleased with the update.

**Comment by yirmio** [comment]
AFAIK this bug should be resolved in the latest version 
https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.217.2

**Comment by KonstantinTyukalov** [comment]
Hi everyone!
> AFAIK this bug should be resolved in the latest version
https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.217.2

Correct, this fix was released in version 2.217.2.
Could you confirm if this fix solved the issue for you?
Thanks!

**Comment by yirmio** [comment]
> Hi everyone!
> 
> > AFAIK this bug should be resolved in the latest version
> > https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.217.2
> 
> Correct, this fix was released in version 2.217.2. Could you confirm if this fix solved the issue for you? Thanks!

Yes, I havent seen this issue with the new release.
Thanks!

**Comment by kirill-ivlev** [comment]
Closing this one, since the issue seems to be resolved starting from 2.217.2.
Thank you for feedbacks!

**Comment by pb185235** [comment]
I am using the actions-runner version 2.316.1 but still getting the error saying "Failed to Lock Service Database for Write" while trying to register an Azure VM as github runner. Please suggest how do we fix it? I am trying to register VM as github runner through "az vm run-command" and using config.cmd.
