### ISSUE TITLE
[BUG]: Sparse checkout feature leads to failures when reusing agents

### ISSUE THREAD

**Issue by PaulVrugt** [microsoft/azure-pipelines-agent#5113]
### What happened?

Since https://github.com/microsoft/azure-pipelines-agent/issues/4325 was merged, we are experimenting with using this feature in our pipelines. 

We are using private agents (currently using a vmss) and we reuse agents for multiple jobs (so we don't use a freshly provisioned agent for each job) for performance and caching reasons. 

However, once we run a job on an agent that previously ran a job with a sparse checkout, the checkout task of the agent doesn't do a full checkout anymore. It seems that git isn't aware of the fact the existing state is in a sparse checkout state, so it doesn't check out all files. This leads to random failures because of missing files in the repository.

### Versions

4.251.0

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell

```

**Comment by Penguinwizzard** [comment]
I suspect this _may_ be fixed by https://github.com/microsoft/azure-pipelines-agent/commit/6bee6b7fe7fd1cb1819c9c9a511d3444c0ce3f49 - it moved the sparse checkout config before the new fetch/checkout, so it should become non-sparse in that flow.

**Comment by jeremytbrun** [comment]
I believe I'm experiencing this issue as well. Hoping the new release will address it.

**Comment by BastiaanMolsbeck** [comment]
Is there any update on this?

**Comment by edolic** [comment]
We have the same issue, we don't even have any repo where one of the new settings sparseCheckoutPatterns or Directory are set and still facing the issue.  Is there a way to set this to false?
```
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: UseGitLongPaths = true Source: $(USE_GIT_LONG_PATHS) 
   Knob: EnableIssueSourceValidation = true Source: $(ENABLE_ISSUE_SOURCE_VALIDATION) 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC_LOG) 
   Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
   Knob: UseNewNodeHandlerTelemetry = True Source: $(DistributedTask.Agent.USENEWNODEHANDLERTELEMETRY) 
   Knob: ProcessHandlerEnableNewLogic = true Source: $(AZP_75787_ENABLE_NEW_PH_LOGIC) 
   Knob: EnableResourceMonitorDebugOutput = true Source: $(AZP_ENABLE_RESOURCE_MONITOR_DEBUG_OUTPUT) 
   Knob: EnableResourceUtilizationWarnings = true Source: $(AZP_ENABLE_RESOURCE_UTILIZATION_WARNINGS) 
   Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
   Knob: FailJobWhenAgentDies = true Source: $(FAIL_JOB_WHEN_AGENT_DIES) 
   Knob: CheckForTaskDeprecation = true Source: $(AZP_AGENT_CHECK_FOR_TASK_DEPRECATION) 
   Knob: CheckIfTaskNodeRunnerIsDeprecated246 = False Source: $(DistributedTask.Agent.CheckIfTaskNodeRunnerIsDeprecated246) 
   Knob: UseNode20ToStartContainer = True Source: $(DistributedTask.Agent.UseNode20ToStartContainer) 
   Knob: LogTaskNameInUserAgent = true Source: $(AZP_AGENT_LOG_TASKNAME_IN_USERAGENT) 
   Knob: UseFetchFilterInCheckoutTask = true Source: $(AGENT_USE_FETCH_FILTER_IN_CHECKOUT_TASK) 
   Knob: Rosetta2Warning = true Source: $(ROSETTA2_WARNING) 
   Knob: AddForceCredentialsToGitCheckout = True Source: $(DistributedTask.Agent.AddForceCredentialsToGitCheckout) 
   Knob: UseSparseCheckoutInCheckoutTask = true Source: $(AGENT_USE_SPARSE_CHECKOUT_IN_CHECKOUT_TASK) 
```

**Comment by bdovaz** [comment]
No stale
