### ISSUE TITLE
[enhancement]: VS2026 / MSBuild 18 Support

### ISSUE THREAD

**Issue by BlueBSH** [microsoft/azure-pipelines-agent#5397]
### Describe your feature request here

When will the VSTS agent properly recognize the new MSBuild 18 with VS 2026? Feels like this should have been there  before the public release, not seeing it in the current releases of the VSTS agents or the preview ones yet.

**Comment by drocx** [comment]
Already asked for in September #5320

**Comment by ehasis** [comment]
We have updated couple of our agent servers to VS 2026 (build tools 18) and they are not recognizing the capabilities. Agent v4.264.2

**Comment by drocx** [comment]
Try this workaround:
https://github.com/microsoft/azure-pipelines-tasks/issues/21319#issuecomment-3486215867

**Comment by FreeFrags** [comment]
Same issue here.

**Comment by romeelian** [comment]
Same here as well and existing capabilities can not be corrected; new ones are not a problem ...

**Comment by durandt** [comment]
I can confirm that azure-pipelines-agent v4.264.2 does not pick up Visual Studio 2026 capabilities on Windows Server 2025.

**Comment by codingaddicted** [comment]
Same here. 
The Azure pipeline executes the vswhere tool with ` -version [17.0,18.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json` parameters which returns the vs 2022 build tools only. I checked with `-all` as suggested [here](https://developercommunity.visualstudio.com/t/Agent-not-recognizing-VS-Build-Tools-202/10999222?space=21&sort=newest#:~:text=1.,Add%20comment%20or%20solution) and it correctly returns all versions installed (2022 and 2026).
```json
[
  {
    "instanceId": "45eb6cf7",
    "installDate": "2025-11-09T16:05:27Z",
    "installationName": "VisualStudio/17.14.20+36705.20",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools",
    "installationVersion": "17.14.36705.20",
    "displayName": "Visual Studio Build Tools 2022",
    "description": "The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications without requiring the Visual Studio IDE. There are options to install the Visual C++ compilers and libraries, MFC, ATL, and C++/CLI support.",
    "updateDate": "2025-11-17T10:21:56.3333216Z",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "resolvedInstallationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools",
    "channelId": "VisualStudio.17.Release",
    "installedChannelId": "VisualStudio.17.Release",
    "channelUri": "https://aka.ms/vs/17/release/channel",
    "installedChannelUri": "https://aka.ms/vs/17/release/channel",
    "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.14#17.14.20",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288"
  },
  {
    "instanceId": "7772d720",
    "installDate": "2025-11-17T10:05:56Z",
    "installationName": "VisualStudio/18.0.0+11205.157",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\18\\BuildTools",
    "installationVersion": "18.0.11205.157",
    "displayName": "Visual Studio Build Tools 2026",
    "description": "Essential MSBuild and compiler tools – no IDE required.",
    "updateDate": "2025-11-17T10:05:56.4887323Z",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "resolvedInstallationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\18\\BuildTools",
    "channelId": "VisualStudio.18.Release",
    "installedChannelId": "VisualStudio.18.Release",
    "channelUri": "https://aka.ms/vs/18/stable/channel",
    "installedChannelUri": "https://aka.ms/vs/18/stable/channel",
    "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/18/release-notes-v18.0#18.0.0",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661480"
  }
]
```

The agent capabilities list on DevOps portal shows 2022 tools paths only.

<img width="887" height="219" alt="Image" src="https://github.com/user-attachments/assets/3450f8e5-8181-48fd-9a0c-c4549e5847be" />

**Comment by ehasis** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/21412

**Comment by fernandezja** [comment]
With the [v4.266.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v4.266.0) release (currently in pre-release), the VS2026 and MSBuild 18 capabilities are now available.
[https://github.com/microsoft/azure-pipelines-agent/releases/tag/v4.266.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v4.266.0)

<img width="862" height="176" alt="Image" src="https://github.com/user-attachments/assets/4b61f796-33bd-44a3-8f33-2bb1e5bcddda" />

**Comment by chrisbardon** [comment]
@fernandezja , I just tried the new agent, and it doesn't seem to work.  The vsbuild task is still running this in my log:

"D:\buildagent-rnd\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.260.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -latest -format json

Which isn't returning VS2026 because of the upper limit on the version (18.0).  This appears to be hardcoded.  Is there something else you need to change to get the vsbuild task to work?

Note that this returns the correct tool paths (omit the version, and just use "latest" as configured):

D:\buildagent-rnd>"D:\buildagent-rnd\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.260.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -latest -format json
[
  {
    "instanceId": "516605d4",
    "installDate": "2025-11-26T18:41:50Z",
    "installationName": "VisualStudio/18.0.2+11222.15",
    "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise",
    "installationVersion": "18.0.11222.15",
    "displayName": "Visual Studio Enterprise 2026",
    "description": "Built for scale, security, and speed – the IDE for complex, high-impact development.",
    "updateDate": "2025-11-26T18:41:50.8447463Z",
    "expirationDate": "2026-02-05T17:00:00+00:00",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "resolvedInstallationPath": "C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise",
    "channelId": "VisualStudio.18.Release",
    "installedChannelId": "VisualStudio.18.Release",
    "channelUri": "https://aka.ms/vs/18/stable/channel",
    "installedChannelUri": "https://aka.ms/vs/18/stable/channel",
    "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/18/release-notes-v18.0#18.0.2",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661480"
  }
]

**Comment by DaveWhite-BL** [comment]
When can we expect an agent version for Azure DevOps Server that supports VS2026?  I can't really use a work-around as I need fully supported software as part of my pipeline.

**Comment by abbweiman** [comment]
Any update on this? After updating our projects to .NET 10 and installing VS2026 on the build agent we get many warnings like _NETSDK1233: Targeting .NET 10.0 or higher in Visual Studio 2022 17.14 is not supported._
The build succeeds but it feels fishy..

**Comment by chrisbardon** [comment]
In this issue (https://github.com/microsoft/azure-pipelines-tasks/issues/21319#issuecomment-3637202156) there's instructions for installing the prerelease versions of the tasks.  I can confirm that if I have vs/latest selected and VS2026 installed that the new tasks work.

**Comment by Smile4ever** [comment]
@tarunramsinghani This issue should be closed, since version 4.266.2 supports Visual Studio 2026.

<img width="1351" height="531" alt="Image" src="https://github.com/user-attachments/assets/811edd16-8845-4124-a1ea-d0d5be6b2740" />

Self hosted can be updated here:

<img width="803" height="719" alt="Image" src="https://github.com/user-attachments/assets/8e88e0ca-6189-49f8-96f7-f7b4c6eb4874" />

**Comment by DaveWhite-BL** [comment]
@Smile4ever I disagree. This issue has indeed been fixed in the version 4 (Azure DevOps) agents, but not the version 3 (Azure DevOps Server {i.e. on-prem server installations})

**Comment by andreascaesar** [comment]
@Smile4ever  I also disagree...
And in November 20026 when VS2027 will be released, the problem will back even if fixed now...
Can't the version check be removed entirely once and for all?
What is the point of checking max version, if I have a problem with a new VS, then the solution is quite simple, just choose the previous version when building...

**Comment by cvocvo** [comment]
> [@tarunramsinghani](https://github.com/tarunramsinghani) This issue should be closed, since version 4.266.2 supports Visual Studio 2026.
> 
> <img alt="Image" width="1351" height="531" src="https://private-user-images.githubusercontent.com/544411/542204386-811edd16-8845-4124-a1ea-d0d5be6b2740.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk3MDE3NTksIm5iZiI6MTc2OTcwMTQ1OSwicGF0aCI6Ii81NDQ0MTEvNTQyMjA0Mzg2LTgxMWVkZDE2LTg4NDUtNDEyNC1hMWVhLWQwZDViZTZiMjc0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOVQxNTQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDcyZWQ4MTQ4MjkyYzFiNWE4OWMxY2YzMTA5OTY2MzE5OWMwYWRkMmU3YmM2MjI1YWRkOGM2MmI4NmJkNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G77dP--oSjF2jbpw8Hu0NKMrSyYfkPf0yoJan7259VQ">
> Self hosted can be updated here:
> 
> <img alt="Image" width="803" height="719" src="https://private-user-images.githubusercontent.com/544411/542204662-8e88e0ca-6189-49f8-96f7-f7b4c6eb4874.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk3MDE3NTksIm5iZiI6MTc2OTcwMTQ1OSwicGF0aCI6Ii81NDQ0MTEvNTQyMjA0NjYyLThlODhlMGNhLTYxODktNDlmOC05NmY3LWY3YjRjNmViNDg3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOVQxNTQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTVhYzFjYThlNmZmOGRhNGNkZWU0NDM4ZTFmYmFjZTkwYjMzYjU1ZmQ0NjE4ZmQ3MmUyMjA4MWFlZDk0NmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DusLoNk2Cf7G4-4vRhYVhAqFSAnvZXAFMNpIMuHsmgs">

I agree with @DaveWhite-BL and @andreascaesar 

Maybe I'm missing something, but how can I update on-prem agents in Azure DevOps Server 2022.2 (AzureDevopsServer_20251024.2) to support .NET 10 builds?
- Our agents are still showing 3.238.0 as of today
- Even the latest release from 12/9/25 doesn't support it? https://devblogs.microsoft.com/devops/announcing-azure-devops-server-general-availability/?commentid=5155#comment-5155
- It's also unclear to me if we need to be doing anything with this as well; it seems there are a bunch of moving parts and pieces and what I really need is a set of steps to get things functional. https://github.com/microsoft/azure-pipelines-tasks/issues/21319#issuecomment-3637202156

**Comment by Frulfump** [comment]
> > [@tarunramsinghani](https://github.com/tarunramsinghani) This issue should be closed, since version 4.266.2 supports Visual Studio 2026.
> > 
> > <img alt="Image" width="1351" height="531" src="https://private-user-images.githubusercontent.com/544411/542204386-811edd16-8845-4124-a1ea-d0d5be6b2740.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk3MDE3NTksIm5iZiI6MTc2OTcwMTQ1OSwicGF0aCI6Ii81NDQ0MTEvNTQyMjA0Mzg2LTgxMWVkZDE2LTg4NDUtNDEyNC1hMWVhLWQwZDViZTZiMjc0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOVQxNTQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDcyZWQ4MTQ4MjkyYzFiNWE4OWMxY2YzMTA5OTY2MzE5OWMwYWRkMmU3YmM2MjI1YWRkOGM2MmI4NmJkNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G77dP--oSjF2jbpw8Hu0NKMrSyYfkPf0yoJan7259VQ">
> > Self hosted can be updated here:
> > 
> > <img alt="Image" width="803" height="719" src="https://private-user-images.githubusercontent.com/544411/542204662-8e88e0ca-6189-49f8-96f7-f7b4c6eb4874.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk3MDE3NTksIm5iZiI6MTc2OTcwMTQ1OSwicGF0aCI6Ii81NDQ0MTEvNTQyMjA0NjYyLThlODhlMGNhLTYxODktNDlmOC05NmY3LWY3YjRjNmViNDg3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOVQxNTQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTVhYzFjYThlNmZmOGRhNGNkZWU0NDM4ZTFmYmFjZTkwYjMzYjU1ZmQ0NjE4ZmQ3MmUyMjA4MWFlZDk0NmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DusLoNk2Cf7G4-4vRhYVhAqFSAnvZXAFMNpIMuHsmgs">
> 
> I agree with @DaveWhite-BL and @andreascaesar 
> 
> Maybe I'm missing something, but how can I update on-prem agents in Azure DevOps Server 2022.2 (AzureDevopsServer_20251024.2) to support .NET 10 builds?
> - Our agents are still showing 3.238.0 as of today
> - Even the latest release from 12/9/25 doesn't support it? https://devblogs.microsoft.com/devops/announcing-azure-devops-server-general-availability/?commentid=5155#comment-5155
> - It's also unclear to me if we need to be doing anything with this as well; it seems there are a bunch of moving parts and pieces and what I really need is a set of steps to get things functional. https://github.com/microsoft/azure-pipelines-tasks/issues/21319#issuecomment-3637202156

To get .NET 10 builds working maybe you could use the `UseDotNet@2` to install the .NET 10 SDK and then use the SDK directly in a script task or use the `DotNetCoreCLI@2` task. But maybe there's something in your build that actually requires the specific task in this issue?

**Comment by PeterStaev** [comment]
This shold not be closed as it is still an issue. I've updated our agent to 4.266.2. Rebooted the machines and the capabilities show correctly v18 of VS and MSBuild. But the VSBuild task still can't find version 18 and build the project with v17. 

<img width="1372" height="68" alt="Image" src="https://github.com/user-attachments/assets/47be40f4-1510-47de-a75d-267b419099cb" />


```yaml
- task: VSBuild@1
  displayName: 'Build solution xxxx'
  inputs:
    solution: 'xxx'
    vsVersion: 18.0
    platform: 'Any CPU'
    configuration: 'Release'
```

**Comment by MrMikeJJ** [comment]
@PeterStaev The agent is updated and fixed.
That is a separate issue in a separate repository ( https://github.com/microsoft/azure-pipelines-tasks )
Which has also been fixed https://github.com/microsoft/azure-pipelines-tasks/issues/21319 . But you will need to update the tasks to make use of it. There are some comments in that thread showing you how to do so.

**Comment by TeddMcAdams** [comment]
Agree this should not be closed AFAIK.  

If you are using "Azure Pipelines" agents and the VSBuild@1 build task (because you have a requirement on `MSBuild` and cannot use `dotnet build`) - then there is no support as VS2026 is not in the `vmImage` yet.   Maybe it is not this team's responsibility, but for tracking I think it would be good to keep this open?

see also: https://github.com/actions/runner-images/issues/13291

**Comment by Eric1243123** [comment]
> Any update on this? After updating our projects to .NET 10 and installing VS2026 on the build agent we get many warnings like _NETSDK1233: Targeting .NET 10.0 or higher in Visual Studio 2022 17.14 is not supported._ The build succeeds but it feels fishy..

Bumping this as I'm having the same problem. 

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v4-agent?view=azure-devops#does-azure-devops-server-support-the-4x-agent

Link even mentions that agent version 4.x will be available for 2020 and later, but we're ~3 months into .NET 10 and this is still unresolved.

**Comment by JeremyJeanson** [comment]
Same case here (agents 4.268.0 on Windows Server 2025 + Build Tools 2026 + Azure DevOps Server).

All 2026 featrues are detected.

But the build throw the error MSB4041 when I am using MSBuild@1 task with a simple MSBuild file.

Agent used msbuild found here :
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe

**Comment by DaveWhite-BL** [comment]
Another quarter without a solution. Why is it taking so long to solve a pretty simple problem? I know that the later versions of the agent software (eg: 4.270) work perfectly, as I have installed them. However Azure DevOps Server downgrades them to 4.260 as part of its normal maintenance. This means I cannot use VS2026 in our infrastructure. 
On another note, I feel like I am banging my head against a brick wall, the last six months. I can't use the latest version of Visual Studio, and I can't migrate from on-prem to cloud as the migration tools have also not been published for 25H2.  What are you guys doing???

**Comment by MrMikeJJ** [comment]
> However Azure DevOps Server downgrades them to 4.260 as part of its normal maintenance. This means I cannot use VS2026 in our infrastructure.

@DaveWhite-BL 
You can prevent that with an system environmental variable, on the build server.

Add Variable: AZP_AGENT_DOWNGRADE_DISABLED
With value: true

Probably need to reboot or restart the agents after adding that.

Also on the Azure Devops Server, make sure you have put the agent zip file in 
C:\ProgramData\Microsoft\Azure DevOps\Agents

**Comment by DaveWhite-BL** [comment]
> Also on the Azure Devops Server, make sure you have put the agent zip file in C:\ProgramData\Microsoft\Azure DevOps\Agents

That worked! Thank you very much indeed!  Now my build fails half-way through, but that's something our dev team can take a look at. While I _really_ appreciate your help, @MrMikeJJ, I think we still need Microsoft to address this issue in a way that doesn't require users to find a solution from someone on the internet.

**Comment by AmitGDev** [comment]
I've successfully integrated the Visual Studio 2026 build tools (MSBuild 18) into a GitHub-hosted runner workflow for a C++ project. Here is how I did it:
https://stackoverflow.com/questions/79852888/how-can-github-hosted-runners-use-visual-studio-2026-build-tools-msbuild-18-fo/79852893#79852893

**Comment by davidgvh** [comment]
Appears to be working after updating to ADO Agent 5.275.0.
